# Generated by Django 3.2.7 on 2021-09-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRBoost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField()),
                ('per_id', models.IntegerField()),
                ('role_per_id', models.IntegerField()),
                ('has', models.BooleanField()),
                ('field', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('role_name', models.CharField(max_length=15)),
            ],
        ),
    ]
