# Generated by Django 3.2.7 on 2021-09-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRBoost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='HRBoost.userrole'),
        ),
    ]
