# Generated by Django 3.2.7 on 2021-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRBoost', '0003_auto_20210928_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservacation',
            name='num_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservacation',
            name='num_hours',
            field=models.IntegerField(default=0),
        ),
    ]
