# Generated by Django 3.2.7 on 2021-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRBoost', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
